#define UNIT_TEST
#include "TestContext.hpp"

#include "FirstSteps.cpp"

#include "BrainSteps.cpp"
#include "BresenhamSteps.cpp"
#include "DungeonMapSteps.cpp"
#include "EffectSteps.cpp"
#include "ElementalDamageSteps.cpp"
#include "EquipmentSteps.cpp"
#include "GameSteps.cpp"
#include "ItemSteps.cpp"
#include "LightSteps.cpp"
#include "MonsterRecallSteps.cpp"
#include "MonsterSteps.cpp"
#include "RangedSteps.cpp"
#include "RectSteps.cpp"
#include "SpeedSteps.cpp"
#include "StringTableSteps.cpp"
#include "TargetSteps.cpp"
#include "TextEntrySteps.cpp"
#include "TilesetSteps.cpp"
#include "UtilSteps.cpp"
#include "VectorSteps.cpp"
#include "VisibleMonstersSteps.cpp"
